### ISSUE TITLE
关于压缩功能

### ISSUE THREAD

**Issue by geekmakersun** [nostarsnow/webpack-multi-seed#2]
我看有压缩html功能，我想问下，怎么开启呢

**Comment by nostarsnow** [comment]
额。我刚更新了一下。
原来配置里是在`config.htmlPlugin.minify`
如果你更新到最新的**pure**分支。位置在`config.build.htmlMinify`

**Comment by geekmakersun** [comment]
看到了优化了html压缩配置，十分感谢，pure分支把参考demo清空了，初次上手，有点无从下手，不知道怎么最大化发挥魅力

**Comment by nostarsnow** [comment]
多谢提醒。我把master分支删了。新增了demo分支。。。
把一些常用的给加上了。
另外。如果你对webpack不是很熟悉。其实我倒不是很建议你用这个。。。
如果使用中遇到问题还请提供。谢谢
