### ISSUE TITLE
关于图片引用问题

### ISSUE THREAD

**Issue by geekmakersun** [nostarsnow/webpack-multi-seed#3]
我想问下，html利用内嵌样式引用背景图该如何调用呢，如图
![](https://gitee.com/sunbingchen/tuchuang/raw/master/20200402103611.png)
1、img标签里的可以显示编译后的，style="background-image: url('_assets/img/home_banner1-bg.jpg');" 里的却不编译
2、编译后的` /img//_assets/ ` 中间有两个/，/pages/index/img//_assets/home_banner1-pic2.5336b68.png

**Comment by sunbingchen92** [comment]
> 我想问下，html利用内嵌样式引用背景图该如何调用呢，如图
> ![](https://camo.githubusercontent.com/f38b4ecebe796f44ae255b8f707b66691ac727c9/68747470733a2f2f67697465652e636f6d2f73756e62696e676368656e2f7475636875616e672f7261772f6d61737465722f32303230303430323130333631312e706e67)
> 1、img标签里的可以显示编译后的，style="background-image: url('_assets/img/home_banner1-bg.jpg');" 里的却不编译
> 2、编译后的`/img//_assets/` 中间有两个/，/pages/index/img//_assets/home_banner1-pic2.5336b68.png

**Comment by geekmakersun** [comment]
第一个问题我用sprite解决了

**Comment by geekmakersun** [comment]
我觉得可以用wiki整理一个使用文档的东西，这个脚手架很给力

**Comment by nostarsnow** [comment]
谢谢。第一个问题。。。确实没有好方法。
style内的无法检测。目前只能通过attribute来检测。或者在css中使用background
比如`img:src` , `img:data-src`。如果添加可以在`webpack.rules.js`中207行。
第二个问题。。。我更新改过了。确实是bug。
而且我发现我公司目前线上使用的也是不符合我预期的。虽然没有出错。哈哈
下面这样才应该是预期的。正常的。
`/pages/index/img/home_banner1-pic2.5336b68.png`

**Comment by geekmakersun** [comment]
> 谢谢。第一个问题。。。确实没有好方法。
> style内的无法检测。目前只能通过attribute来检测。或者在css中使用background
> 比如`img:src` , `img:data-src`。如果添加可以在`webpack.rules.js`中207行。
> 第二个问题。。。我更新改过了。确实是bug。
> 而且我发现我公司目前线上使用的也是不符合我预期的。虽然没有出错。哈哈
> 下面这样才应该是预期的。正常的。
> `/pages/index/img/home_banner1-pic2.5336b68.png`

第一个问题我注意到了`ebpack.rules.js`中207行，不过不太会调，我加的没效果，不过用精灵图也挺好的

第二个问题我发现中间再加一级分类就可以了，图片分类一下倒也可以

**Comment by nostarsnow** [comment]
第一个style内确实无法识别。即使是vue也没能做到。要么就按你的思路用精灵图。要么就在css中引入。
第二个问题。是我url匹配的bug。已修复。。。如果你还有兴趣更新的话
