### ISSUE TITLE
关于htmlReplace的问题

### ISSUE THREAD

**Issue by geekmakersun** [nostarsnow/webpack-multi-seed#4]
我看到`config.js`里面有个htmlReplace配置域名，想问下怎么使用呢，原来master分支我注意到有个cdn引用位置，换成了demo，我看好像也删除了

**Comment by geekmakersun** [comment]
因为，build编译后的资源引用的是根目录的，https://dev1.junke158.cn/dist/    我用coding部署的静态网站，资源加载都错误了

我觉得webpack深入学习一下，还是很好用的

**Comment by nostarsnow** [comment]
`htmlReplace`直接在html里写就是了。
比如`config.js`中。你在html写`__VERSION__`就会替换成`3.0`

**Comment by nostarsnow** [comment]
> 因为，build编译后的资源引用的是根目录的，https://dev1.junke158.cn/dist/ 我用coding部署的静态网站，资源加载都错误了
> 
> 我觉得webpack深入学习一下，还是很好用的

打包后前缀在`config.build.assetsPublicPath`中修改。就比如你的网址（我们公司也是用的coding做git）。
`assetsPublicPath: '/dist/'`
或者
`assetsPublicPath: '../dist/'`
`assetsPublicPath: 'https://dev1.junke158.cn/dist/'`

**Comment by nostarsnow** [comment]
我非常担心我这个webpack工具会把你引入邪道。。。
因为很多功能一点儿都不webpack。如果可以你也多尝试尝试其他的顺便研究一下自己从零搭建个webpack脚手架吧

**Comment by geekmakersun** [comment]
哈哈哈。我觉得用的顺手就好了，慢慢过渡呗。。。另外，你指的邪道是？

**Comment by nostarsnow** [comment]
> 哈哈哈。我觉得用的顺手就好了，慢慢过渡呗。。。另外，你指的邪道是？

因为其他所有的webpack多页面工具都不是这样的模式。尤其是对于文件的处理，完全的gulp理念

**Comment by geekmakersun** [comment]
> > 因为，build编译后的资源引用的是根目录的，https://dev1.junke158.cn/dist/ 我用coding部署的静态网站，资源加载都错误了
> > 我觉得webpack深入学习一下，还是很好用的
> 
> 打包后前缀在`config.build.assetsPublicPath`中修改。就比如你的网址（我们公司也是用的coding做git）。
> `assetsPublicPath: '/dist'`
> 或者
> `assetsPublicPath: '../dist'`
> `assetsPublicPath: 'https://dev1.junke158.cn/dist/'`

感谢你写的这三个参考代码，又搞懂了一些。。

**Comment by sunbingchen92** [comment]
> > 因为，build编译后的资源引用的是根目录的，https://dev1.junke158.cn/dist/ 我用coding部署的静态网站，资源加载都错误了
> > 我觉得webpack深入学习一下，还是很好用的
> 
> 打包后前缀在`config.build.assetsPublicPath`中修改。就比如你的网址（我们公司也是用的coding做git）。
> `assetsPublicPath: '/dist'`
> 或者
> `assetsPublicPath: '../dist'`
> `assetsPublicPath: 'https://dev1.junke158.cn/dist/'`

感谢你写的这三个参考代码，又搞懂了一些。。

**Comment by geekmakersun** [comment]
> > 哈哈哈。我觉得用的顺手就好了，慢慢过渡呗。。。另外，你指的邪道是？
> 
> 因为其他所有的webpack多页面工具都不是这样的模式。尤其是对于文件的处理，完全的gulp理念

看了你之前那个master分支的，似乎是我之前在github上找webpack脚手架的其中一个，刚接触webpack，用的我一脸懵逼，用过其他一个，个人用的没你现在这个高效。

我是用开模块化开发模版，然后套用到内容管理系统，你这种文件处理模式，个人感觉没什么不好

**Comment by sunbingchen92** [comment]
> > 哈哈哈。我觉得用的顺手就好了，慢慢过渡呗。。。另外，你指的邪道是？
> 
> 因为其他所有的webpack多页面工具都不是这样的模式。尤其是对于文件的处理，完全的gulp理念

看了你之前那个master分支的，似乎是我之前在github上找webpack脚手架的其中一个，刚接触webpack，用的我一脸懵逼，用过其他一个，个人用的没你现在这个高效。

我是用开模块化开发模版，然后套用到内容管理系统，你这种文件处理模式，个人感觉没什么不好

**Comment by geekmakersun** [comment]
很多webpack或许更适用于单页面，我目前需要的是多页面的

**Comment by nostarsnow** [comment]
我也觉得这个适合多页面。就是因为不喜欢他们搞的貌似多页其实还是单页理念的解决方案。
在公司里用了很久了。我做新的多页项目也是用的这个。
不过`master`分支一直都没怎么更新过倒是。哈哈。所以我直接给删了。
有什么问题随时联系。谢谢
