### ISSUE TITLE
一个关于引入到html的编译后的css、js资源带版本号的小建议

### ISSUE THREAD

**Issue by geekmakersun** [nostarsnow/webpack-multi-seed#5]
网站接入了CDN功能后，修改了一些样式后，因为html被CDN缓存了，所以上传替换新编译后的资源不会自动生效，需要手动刷新或者等html缓存失效后才行。
<pre>
build: {
    assetsRoot: path.dist,
    assetsSubDirectory: path.dist,
    assetsPublicPath: 'https://dev1.junke158.cn/dist/',
    bundleAnalyzerReport: process.env.npm_config_report,
    hash: true,
    uglify: true,
    cssmin: true,
    htmlMinify: false,
    htmlBeautify: true,
    includeDir: [],
  },
</pre>
如果静态资源带版本号的话，就可以解决这个问题

**Comment by nostarsnow** [comment]
hash就是解决静态资源版本号的问题的。
你设置`hash:true`之后。如果有改动。html中的css和js的hash会改变。
你遇到的问题是cdn对于html的缓存。那这不是前端可以解决的。要不修改cdn缓存过滤。要么。。。
我倒是可以给你个方便的解决思路
访问的时候手动带个版本号。比如
`https://dev1.junke158.cn/dist/?12387219472190847210472102471042187`

**Comment by geekmakersun** [comment]
> hash就是解决静态资源版本号的问题的。
> 你设置`hash:true`之后。如果有改动。html中的css和js的hash会改变。
> 你遇到的问题是cdn对于html的缓存。那这不是前端可以解决的。要不修改cdn缓存过滤。要么。。。
> 我倒是可以给你个方便的解决思路
> 访问的时候手动带个版本号。比如
> `https://dev1.junke158.cn/dist/?12387219472190847210472102471042187`

了解了，也是，可以套用cms模版的时候加版本号
