### ISSUE TITLE
关于满屏的”↹↹“的问题

### ISSUE THREAD

**Issue by geekmakersun** [nostarsnow/webpack-multi-seed#6]
复制了一段之前项目应该没问题的一段js代码，瞬间满屏` Replace `↹↹` with` `

改成了`"prettier/prettier": "warn",`或 `"prettier/prettier": "off"`就正常了，查了半天，也没研究明白该怎么从根本解决
<pre>
"rules": {
			"prettier/prettier": "warn",
			"generator-star-spacing": "off"
		},
</pre>

**Comment by nostarsnow** [comment]
这个。。。是因为添加了eslint。
如果你用vscode的话。可以安装eslint和prettier插件。然后使用快捷键一键格式化。
如果你不想要eslint。你需要。。。
`config.dev.eslint=false`

**Comment by geekmakersun** [comment]
> 这个。。。是因为添加了eslint。
> 如果你用vscode的话。可以安装eslint和prettier插件。然后使用快捷键一键格式化。
> 如果你不想要eslint。你需要。。。
> `config.dev.eslint=false`

那个规范提交说明的插件是不是prettier来着，忘了是哪个插件，规范标准化挺好的。使用的编辑器安装了插件，似乎关闭了可以避免一些冲突。我发现，似乎跟使用的format插件有些配置产生的冲突

**Comment by geekmakersun** [comment]
你配置的可以查出更多的潜在的资源引用问题，还是不用一刀切的好，只是把` "prettier/prettier": "warn" `就好了，有可能问题还是提醒一下的好，不那么激进。反正提醒你了，解不解决就是你的事情了。

另外，据我查的一些资料，上面那个问题似乎是因为使用的不用开发环境。比如linux和window，有些编码格式的差异

**Comment by nostarsnow** [comment]
> 你配置的可以查出更多的潜在的资源引用问题，还是不用一刀切的好，只是把`"prettier/prettier": "warn"`就好了，有可能问题还是提醒一下的好，不那么激进。反正提醒你了，解不解决就是你的事情了。
> 
> 另外，据我查的一些资料，上面那个问题似乎是因为使用的不用开发环境。比如linux和window，有些编码格式的差异

你说的。。。也很有道理。vue cli其实在选择了eslint之后也有同样问题。需要手动调整`devServer.overlay`。或许我应该配置的更简单一些。不是把eslint设置为warn，而是应该设置`devServer.overlay.(warnings|errors)=false`
规范git提交的插件是`husky`和`commit-msg`。同时commit时进行了`eslint`。
开发中的`eslint`，因为是用在公司项目里，所以规范强提醒。也是强制使用'vscode'+`eslint`+`prettier`来规范代码。

**Comment by geekmakersun** [comment]
强制规范代码好，看了你的设置后似懂非懂，看懂了意思，还不清楚怎么个配置方法。。等以后再回来看看吧
